version: "3.8"

services:
  rx_guardian_mysql_docker_service:
    image: mysql:8.0
    container_name: rx_sql
    ports:
      - "${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}"   # host:container (9696:3306)
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - rx_guradian_docker_data:/var/lib/mysql

  rx_guradian_node_backend_service:
    build: .
    container_name: rx_node
    ports:
      - "${NODE_PORT}:${NODE_INTERNAL_PORT}"
    env_file: .env
    depends_on:
      - rx_guardian_mysql_docker_service
      - rx_guardian_redis_service
    volumes:
      - .:/app

  rx_guardian_redis_service:
    image: redis/redis-stack:latest
    container_name: rx_redis
    ports:
      - "${REDIS_EXTERNAL_PORT}:${REDIS_INTERNAL_PORT}"
      - "8001:8001"

volumes:
  rx_guradian_docker_data:
    driver: local
