version: "3.8"

services:
  rx_guardian_redis_service:
    image: redis/redis-stack:latest
    container_name: rx_redis
    env_file: .env
    ports:
      - "${REDIS_EXTERNAL_PORT}:${REDIS_INTERNAL_PORT}"

volumes:
  rx_guradian_docker_data:
    driver: local